python -m pip install --upgrade pip
pip install -U argparse
pip install -U autopep8
pip install -U bandit
pip install -U bokeh
pip install -U bs4
pip install -U Django
pip install -U facebook-sdk
pip install -U Flake8
pip install -U Flask
pip install -U geopy
pip install -U google-api-python-client
pip install -U jupyter
pip install -U jupyterlab
pip install -U keras
pip install -U lxml
pip install -U matplotlib
pip install -U mypy
pip install -U nltk
pip install -U notebook
pip install -U numpy
pip install -U oauth2client
pip install -U opencv-python
pip install -U pandas
pip install -U Pillow
pip install -U prospector
pip install -U pycodestyle
pip install -U pydocstyle
pip install -U pylama
pip install -U pylint
pip install -U pytest
pip install -U PyYAML
pip install -U pyzbar
pip install -U requests
pip install -U scikit-learn
pip install -U scipy
pip install -U seaborn
pip install -U simplejson
pip install -U statsmodels
pip install -U tensorflow
pip install -U tweepy
pip install -U urllib3
pip install -U virtualenv
pip install -U xlrd
